- components/checkout/CompleteCheckoutButton.tsx
- pages/cart.tsx
- fix payment button styles
- fix cart page blank when no checkout
> Fixes-pack-2

- .github/workflows/main.yml
- .github/workflows/stale.yml
- increase delay for stale label
- run build in the CI
> Ci improvements

- README.md
> Add CodeSandbox link to the readme

- LICENSE
> add BSD (3-clause) license

- .github/workflows/main.yml
- README.md
- package.json
- pnpm-lock.yaml
- add package lost during the rebase
- Update the readme
- Add CI job to check if routes are updated
> Paths docs

- codegen.yml
- components/AddressBookCard.tsx
- components/checkout/AddressForm.tsx
- components/checkout/SavedAddressSelectionList.tsx
- components/checkout/ShippingAddressSection.tsx
- lib/regions.ts
- saleor/api.tsx
Client bundle size before: 731 KB
after:  693 KB
(gzipped 219 vs 206)
> Enums-as-types

- components/product/AttributeDetails.tsx
- package.json
- pnpm-lock.yaml
React 18 is now available as a Release Candidate: https://github.com/reactwg/react-18/discussions/9
Projects are encouraged to test it out.
> Prepare the migration path for React 18

- pages/[channel]/[locale]/account/orders/[token].tsx
- pages/[channel]/[locale]/category/[slug].tsx
- pages/[channel]/[locale]/collection/[slug].tsx
- pages/[channel]/[locale]/index.tsx
- pages/[channel]/[locale]/page/[slug].tsx
- pages/[channel]/[locale]/products/[slug].tsx
To minimize amount of the requests during the build time Ive turned off the PDP generation during the build time
> Throttle PDP SSR and use "blocking" fallback

- components/product/ProductGallery.tsx
- package.json
- pnpm-lock.yaml
Use the `priority` of `<Image />` as described [here](https://nextjs.org/docs/api-reference/next/image#priority)
> use image priority on product page

- .dockerignore
- Dockerfile.dev
- nginx/dev.conf
- add dev dockerfile 
- add nginx proxy to resolve networking in saleor-platform scenario on non-linux machines
> Add docker and saleor-platform configuration

- components/Pagination/Pagination.tsx
Fix the total items counter in the pagination component.
> Fix pagination counter

- pages/[channel]/[locale]/cart.tsx
The difference between the state of the server and local env (checkout is available locally only) was causing a hydration error on the cart page.
> Resolve issue with the hydration step

- components/Footer/Footer.module.css
- components/Footer/Footer.tsx
- graphql/fragments/MenuItemFragment.graphql
- lib/menus.ts
- saleor/api.tsx
In this PR I want to fix issue with no support of external links.
ClickUp task: https://app.clickup.com/t/2549495/SALEOR-6660
> Fix external links in footer menus

- components/Button/Button.tsx
- components/DemoBanner/DemoBanner.tsx
- components/HomepageBlock/HomepageBlock.tsx
- components/Pagination/Pagination.tsx
- components/ProductCard/ProductCard.tsx
- components/ProductCollection/ProductCollection.tsx
- components/RichText/RichText.tsx
- components/checkout/AddressDisplay.tsx
- components/checkout/AddressForm.tsx
- components/checkout/CompleteCheckoutButton.tsx
- components/checkout/EmailSection.tsx
- components/checkout/ShippingAddressSection.tsx
- components/checkout/ShippingMethodDisplay.tsx
- components/checkout/ShippingMethodOption.tsx
- components/checkout/payments/DummyCreditCardSection.tsx
- components/checkout/payments/PaymentSection.tsx
- components/product/AttributeDetails.tsx
- components/product/VariantSelector.tsx
- lib/util.ts
- pages/[channel]/[locale]/products/[slug].tsx
- styles/globals.css
- add missing text-base classes
- modify rich text block
> Typography sizes

- components/CheckoutLineItem/CheckoutLineItem.tsx
- pages/[channel]/[locale]/cart.tsx
Patch for the current cart page. Scaled down the line items to avoid issues with the breaking layout.
> Scale line items in the mobile cart view

- README.md
Prettier applied to the readme.
> Fix formatting in the readme file

- pages/[channel]/[locale]/account/register.tsx
> Fix type of the register form

- pages/[channel]/[locale]/account/addressBook.tsx
> Add missing key for the address book cards

- README.md
There's already an existing deployment section.
> Remove duplicated Vercel deploy button

- pages/[channel]/[locale]/search.tsx
- style touchups
- solved the issue with the empty query error
> Fix search with empty query and adjust styles

- components/product/VariantSelector.tsx
- pages/[channel]/[locale]/products/[slug].tsx
- tailwind.config.js
- price is now displayed on variant selector when products has more variants
- animated 🎉  variant selection
> Redesigned Variant selector

- .eslintrc
- components/HomepageBlock/HomepageBlock.tsx
- components/NavigationAnchor/NavigationAnchor.tsx
- components/PageHero/PageHero.tsx
- components/ProductCollection/ProductCollection.tsx
- components/Spinner/Spinner.tsx
- components/productList/FilteredProductList/FilterDropdown.tsx
- components/productList/FilteredProductList/FilterPills.tsx
- cypress/e2e/filteringProducts.cy.ts
- cypress/e2e/sample.cy.ts
- cypress/elements/category.ts
- cypress/elements/filters.ts
- cypress/elements/navigation.ts
- cypress/elements/shared.ts
- cypress/support/shared.ts
- cypress/tsconfig.json
Adding tests for filters. 
Adding `data-testid` to elements.
> Add tests for filters srs 03

- components/CheckoutLineItem/CheckoutLineItem.tsx
- components/product/VariantSelector.tsx
- cypress/e2e/addVariantToCart.cy.ts
- cypress/elements/cart.ts
- cypress/elements/product-page.ts
- cypress/fixtures/search.ts
- cypress/support/commands.ts
- cypress/support/index.d.ts
- cypress/support/pages/product-page.ts
- cypress/support/pages/search.ts
- pages/[channel]/[locale]/products/[slug].tsx
adding a test of adding products to the cart
adding `data-testid` to elements
adding command for search request
> Add test for add variant to cart

- components/Footer/Footer.tsx
- cypress/e2e/navigation.cy.ts
- cypress/elements/shared-elements.ts
- cypress/support/pages/category.ts
- cypress/support/shared-operations.ts
- adding `data-testid`,
- adding function for opening all internal links in footer,
- adding tests for opening external/internal links,
Additional information: 
I was trying to add function to open all available external links, but I did not achieve this. So I decided to create test with opening only one external link.
> Adding tests for navigation

- README.md
> Fix broken link to configuration.md (#341)

- apps/storefront/components/Navbar/Navbar.tsx
- apps/storefront/pages/[channel]/[locale]/account/login.tsx
This PR disables authentication in storefront (login button in navbar, login page).
Fixes: #345
Long term solution: https://github.com/saleor/react-storefront/issues/351
> Disable auth in storefront

- README.md
Could be a good to mention portfolio on top when stripe is merged.
> Add payment gateways to the intro

- apps/storefront/.eslintrc.js
- apps/storefront/components/seo/BaseSeo.tsx
- apps/storefront/package.json
- apps/storefront/pages/_app.tsx
- pnpm-lock.yaml
> Fixing og image and og url settings

- apps/saleor-app-checkout/next.config.js
- apps/storefront/components/Navbar/Navbar.tsx
- apps/storefront/next.config.js
- apps/storefront/pages/[channel]/[locale]/account/login.tsx
- apps/storefront/pages/[channel]/[locale]/cart.tsx
Rewrite /checkout in storefront to external checkout URL to avoid domains mismatch and auth problem.
Rel: #351
> Rewrite /checkout to external checkout

- apps/storefront/pages/[channel]/[locale]/cart.tsx
- packages/checkout-storefront/src/hooks/useErrors/useCountrySelect.tsx
- packages/checkout-storefront/src/index.tsx
- packages/checkout-storefront/src/lib/utils/utils.ts
- packages/checkout-storefront/src/pages/[channel]/[locale]/Root.tsx
- packages/checkout-storefront/src/pages/_app.tsx
- packages/checkout-storefront/src/sections/Addresses/ShippingAddressSection.tsx
- packages/checkout-storefront/src/sections/Addresses/countries.ts
This also adds base for using channel and language passed from checkout
> Pass country language channel from storefront to checkout

- apps/saleor-app-checkout/backend/payments/createOrder.ts
- apps/saleor-app-checkout/backend/payments/getOrderDetails.ts
I figured we might as well add this commit to the main branch. It doesn't break anything.
> DEMO FIX: Use dummy email

- apps/storefront/components/product/ProductGallery.tsx
- apps/storefront/pages/[channel]/[locale]/products/[slug].tsx
> Design nudges

- apps/storefront/components/ProductCard/ProductCard.tsx
- apps/storefront/components/product/VariantSelector.tsx
Removes levitaion effect on hover
> Remove levitation effect on hover

- .husky/pre-commit
- .husky/pre-push
- .lintstagedrc.js
- packages/checkout-storefront/package.json
> Run eslint and i18n on pre-push

- apps/saleor-app-checkout/content/locales/pl.json
- packages/checkout-storefront/content/locales/pl-PL.json
- packages/checkout-storefront/src/components/AddressForm/AddressForm.tsx
- packages/checkout-storefront/src/hooks/useAddressFormUtils/useAddressFormUtils.ts
- packages/checkout-storefront/src/hooks/useAlerts/useAlerts.tsx
- packages/checkout-storefront/src/hooks/useFormattedMessages/useFormattedMessages.ts
- packages/checkout-storefront/src/hooks/usePay.ts
- packages/checkout-storefront/src/lib/utils/utils.ts
- packages/checkout-storefront/src/sections/CheckoutForm/useCheckoutFinalize.ts
- packages/checkout-storefront/src/sections/CheckoutForm/useCheckoutForm.ts
- packages/checkout-storefront/src/sections/CheckoutForm/useCheckoutFormValidation.ts
- packages/checkout-storefront/tsconfig.json
3 checkout ui fixes for the price of one:
- address form showing up errors on all fields immediately after anything is typed in any one field
- order confirmation view crashing due to locale not being passed to the url
- checkout crashing on pay because of missing useCallbacks and infinite loop happening
Also locales are formatted by the plugin after recent changes regarding prettier on push
> Checkout ui fixes

- packages/checkout-storefront/src/sections/Summary/SummaryStyles.css
- packages/checkout-storefront/src/views/Checkout/CheckoutStyles.css
> Add outline for the summary table

- packages/checkout-storefront/src/hooks/usePay.ts
- packages/checkout-storefront/src/sections/PaymentSection/AdyenDropIn/AdyenDropIn.tsx
- packages/checkout-storefront/src/sections/PaymentSection/AdyenDropIn/createAdyenCheckout.ts
> Adyen Dropin improvements

- apps/saleor-app-checkout/content/locales/es.json
- packages/checkout-storefront/content/locales/es-ES.json
Added Spanish translations for the files:
`en-US.json` -> `es-ES.json`
`en.json` -> `es.json
#541
> Added Spanish translations ('es.json' & 'es-ES.json') files

- packages/checkout-common/package.json
- packages/checkout-storefront/package.json
- packages/ui-kit/package.json
> Solve TypeError: Unknown file extension ".json" on Node 16

- apps/saleor-app-checkout/pages/api/drop-in/adyen/payments/details.ts
- apps/saleor-app-checkout/pages/api/drop-in/adyen/payments/index.ts
- apps/saleor-app-checkout/pages/api/drop-in/adyen/sessions.ts
- apps/saleor-app-checkout/pages/api/pay.ts
- apps/saleor-app-checkout/pages/api/payment-provider-settings.ts
- apps/saleor-app-checkout/pages/api/sentry_sample_error.ts
- apps/saleor-app-checkout/pages/api/set-payment-provider-settings.ts
- apps/saleor-app-checkout/pages/api/webhooks/mollie.ts
- apps/saleor-app-checkout/pages/api/webhooks/saleor/transaction-action-request.ts
- apps/saleor-app-checkout/pages/api/webhooks/stripe.ts
Make sure we also `console.error(…)` errors for users who don't use Sentry.
> Add logs around errors

- apps/saleor-app-checkout/backend/payments/errors.ts
- apps/saleor-app-checkout/backend/payments/providers/adyen/middlewares.ts
- apps/saleor-app-checkout/backend/payments/providers/mollie/utils.ts
- apps/saleor-app-checkout/backend/payments/providers/stripe/stripeClient.ts
- apps/saleor-app-checkout/pages/api/webhooks/adyen.ts
- apps/saleor-app-checkout/pages/api/webhooks/mollie.ts
- apps/saleor-app-checkout/pages/api/webhooks/stripe.ts
> #582: Gracefuly handle missing payment provider credentials

- packages/checkout-storefront/src/hooks/useAlerts/AlertStyles.css
- packages/checkout-storefront/src/sections/Summary/Summary.tsx
> #482 Add min-height to summary items

- .lintstagedrc.js
- apps/checkout/.eslintrc.js
- apps/saleor-app-checkout/.eslintrc.js
- apps/saleor-app-checkout/backend/payments/providers/adyen/createPayment.ts
- apps/storefront/.eslintrc.js
- packages/checkout-common/.eslintrc.js
- packages/checkout-common/src/utils.ts
- packages/checkout-storefront/.eslintrc.js
- packages/eslint-config-checkout/package.json
- pnpm-lock.yaml
> #286 Forbid imports across packages and apps

- packages/checkout-storefront/src/sections/OrderInfo/PaymentSection.tsx
> #632 Remove pay button from the confirmation screen

- apps/saleor-app-checkout/frontend/components/elements/AppProvider/ClientAppBridgeProvider.tsx
- apps/saleor-app-checkout/package.json
- pnpm-lock.yaml
> Fix AppBridge not being able to get the token or receive handshake

- apps/saleor-app-checkout/frontend/components/elements/AppProvider/ClientAppBridgeProvider.tsx
> Make sure checkout app's API client is initialized with token

- apps/storefront/components/BurgerMenu/BurgerMenu.tsx
- apps/storefront/components/Navbar/Navbar.tsx
Fixes https://github.com/saleor/react-storefront/issues/661
> Fix hydration warning when user is logged in

- cypress/elements/checkout/checkout-page.ts
- cypress/fixtures/addresses.json
- cypress/support/commands.ts
I want to merge this because it fixes test for buying as anonymous user.
> Update fillUpBasicAddress with phone

- packages/checkout-storefront/src/lib/utils/address.ts
- packages/checkout-storefront/src/sections/BillingAddressSection/BillingAddressSection.tsx
- packages/checkout-storefront/src/sections/Contact/SignInForm.tsx
- packages/checkout-storefront/src/sections/ShippingAddressSection/ShippingAddressSection.tsx
> Fix getAddressInputData #674

- .github/workflows/e2e.yml
- cypress.config.ts
- add a new environment to run tests
- change default env to run daily tests
- add variables for demo and non-demo environments
> Add new env e2e workflow

- packages/checkout-storefront/src/components/Checkbox.tsx
- packages/checkout-storefront/src/components/Select.tsx
- packages/checkout-storefront/src/hooks/useForm/types.ts
- packages/checkout-storefront/src/hooks/useForm/useForm.ts
- packages/checkout-storefront/src/sections/AddressList/useAddressListForm.ts
- packages/checkout-storefront/src/sections/DeliveryMethods/useDeliveryMethodsForm.ts
- packages/checkout-storefront/src/sections/GuestBillingAddressSection/useBillingSameAsShippingForm.ts
- packages/checkout-storefront/src/sections/GuestUser/useGuestUserForm.ts
- packages/checkout-storefront/src/sections/UserBillingAddressSection/UserBillingAddressSection.tsx
Fixes https://github.com/saleor/react-storefront/issues/760
Also fixes https://github.com/saleor/react-storefront/issues/759
> Fix checkout finalize bugs

- README.md
This PR updates version of `pnpm` showcased in README so that it matches our configuration in `pacakge.json`
> Update version of pnpm to use in README

- cypress/e2e/demo/demo.cy.ts
- cypress/elements/login-page.ts
- cypress/elements/navigation.ts
- cypress/support/commands.ts
- cypress/support/index.d.ts
Those basic tests should confirm basic elements on the home page and log-in process which does not need providing credentials since they are already placed
> demo page tests - home page display and log in user

- .github/workflows/e2e.yml
I want to merge this change to run the nightly tests against demo staging
> Update default nightly test env

- src/app/cart/CheckoutButton.tsx
- src/app/cart/page.tsx
- src/app/products/[slug]/AddButton.tsx
- src/app/products/[slug]/page.tsx
- src/checkout/components/Button.tsx
- src/checkout/sections/SignIn/SignIn.tsx
- src/ui/components/Footer.tsx
- src/ui/components/Nav.tsx
Description of provided changes in commits comments.
> fix: make submit buttons more accessible, few small fixes related to responsiveness

- src/app/cart/CheckoutLink.tsx
- src/app/cart/page.tsx
- src/app/categories/[slug]/page.tsx
- src/app/page.tsx
- src/app/products/page.tsx
- src/ui/components/Footer.tsx
- src/ui/components/VariantSelector.tsx
- Improve accessibility of the VariantSelector (inc. replace buttons with radio inputs).
- Add missed headings and adjust existing ones.
- Disable link to checkout when there is no items in cart.
> fix: fixes related to a11y

- src/app/(main)/cart/DeleteLineButton.tsx
- src/app/(main)/cart/actions.ts
- src/app/(main)/cart/page.tsx
- src/graphql/CheckoutDeleteLines.graphql
- src/graphql/CheckoutFind.graphql
Fix #901 issue.
- Add ability to remove lines from cart.
- Refactor styles in cart - adjust existed, add information about choosed variant, add link to product, etc.
Below comparison before/after:
> feat/refactor: add ability to remove item from cart, refactor cart styels

- src/app/(main)/products/[slug]/page.tsx
- src/graphql/ProductDetails.graphql
- src/ui/components/AvailabilityMessage.tsx
- src/ui/components/VariantSelector.tsx
> fix: fix availability message and variant selectors

- src/ui/components/ProductsList.tsx
Given that our sample database is quite small 3 columns makes catalog look fuller
> Change to 3 columns

- src/app/globals.css
> Switch to gray

- src/app/(main)/products/[slug]/page.tsx
- src/graphql/ProductDetails.graphql
Show price range on the product detail page similarly to product list page
> Use range as price

- package.json
- pnpm-lock.yaml
> Fix `getSetCookie` is not a function

- .eslintrc.json
> Error when checkout imports anything next.js-specific

- src/ui/components/nav/components/MobileMenu.tsx
Fix missing transition after closing the mobile menu.
> fix: fix mobile menu transition

- playwright.config.ts
Added improvements suggested by @wojteknowacki
> Improve e2e workflow

- src/app/checkout/page.tsx
- src/checkout/assets/images/SaleorLogo.tsx
- src/checkout/components/Button.tsx
- src/checkout/components/ErrorContentWrapper.tsx
- src/checkout/components/LinkAsButton.tsx
- src/checkout/sections/Summary/Summary.tsx
- src/checkout/views/Checkout/Checkout.tsx
- src/checkout/views/EmptyCartPage/EmptyCartPage.tsx
- src/checkout/views/PageNotFound/PageNotFound.tsx
Fixes #902 issue.
Changes: 
1. Fix checout background.
2. Fix empty cart page view in checkout:
3. Fix not found page view in checkout:
> fix: fix checkout views

- package.json
- pnpm-lock.yaml
- src/app/(main)/products/[slug]/page.tsx
- Change the OG image for the product page to the product image instead of the default OG image.
- Add JSON-LD for product pages.
> feat: add json-ld and individual og image for single product page

- src/app/(main)/search/page.tsx
- src/graphql/SearchProducts.graphql
- src/ui/components/nav/Nav.tsx
- src/ui/components/nav/components/SearchBar.tsx
Styled in Tailwind and the Search icon was taken from [Lucide](https://lucide.dev/icons/search)
**View on home screen**
---
**View on search results**
---
**View on no results**
---
**View on mobile**
> Feature: Added searchBar

- package.json
- pnpm-lock.yaml
- src/app/checkout/page.tsx
- src/app/layout.tsx
- src/ui/components/nav/components/MobileMenu.tsx
Update TailwindCSS to v3.4 and refactor some arbitrary values.
> chore: update tailwindcss

- README.md
> Update CLI command

- src/hooks/useSelectedPathname.ts
- src/ui/components/nav/components/NavLink.tsx
> Fix Active Nav Link

- .graphqlrc.ts
Addresses #1121 as well as an issue faced in the discord thread "Combinatorics"
> Fix: Add Hour to graphqlrc

- package.json
- pnpm-lock.yaml
fixes security issue with "cookies" package
> Update auth sdk package
