saleor/storefront

components/AccountBaseTemplate.tsx, components/Navbar.tsx, components/NavigationPanel.tsx
- before account section triggers the redirection, now it waits for token refresh operation. Too early redirections are resolved now.
- fix account section link
- unify menu naming
=> Fix redirection issue at `account` and other minor fixes

pages/_app.tsx
Before the first Saleor API call dns needs to be resolved. Preconnect allow us to do that before JS will launch its queries.
=> Dns prefetch to the Saleor API

.env, components/checkout/payments/DummyCreditCardSection.tsx, components/checkout/payments/StripeCreditCardSection.tsx, components/product/VariantSelector.tsx, graphql.schema.json, lib/const.ts, next.config.js, pages/[channel]/[locale]/account/orders/[token].tsx, pages/[channel]/[locale]/checkout.tsx, pages/[channel]/[locale]/index.tsx, pages/[channel]/[locale]/order.tsx, pages/[channel]/[locale]/products/[slug].tsx, pnpm-lock.yaml, saleor/api.tsx
Changes:
- variant selector as a select widget
- payment details prepopulated for the DEMO mode
- changed links after order completed
- fixed layout for the account pages
- image optimization will allow for the images from API endpoint out of the box (instead of hardcoded value)
- redirection out of the checkout pages if the cart is empty
=> Configurable homepage, changed variant selector, bugfixes

components/RegionDialog/RegionDialog.tsx
- clicking outside of the modal closes it. Same for the hitting the escape button
- headless UI provides additional aria args
=> Use headless component for the modal

README.md, docs/configuration.md, docs/translations.md
- use pnpm instead of npm in the readme
- add new docs:
- configuration page (how to configure API endpoint, channels)
- how to manage translations
=> Add docs pages

package.json, pnpm-lock.yaml
The latest version of the pnpm throws an error if there are issues with unmet dependencies/wrong version used. 
Submitted patch adds missing graphql-tag dependency and whitelist react 18 and graphql 16 as valid packages.
PNPM docs: https://pnpm.io/errors#err_pnpm_peer_dep_issues
=> Fix missing dependencies

cypress/e2e/filteringProducts.cy.ts, cypress/e2e/search.cy.ts, cypress/elements/search-page.ts, cypress/elements/shared-elements.ts, cypress/support/commands.ts, cypress/support/pages/category.ts, cypress/support/pages/main-page.ts, cypress/support/shared-operations.ts, cypress/support/shared.ts, package.json
- adding `' '` characters at `data-testid` selectors,
- adding empty lines between variables, 
- changing names of the files `shared` -> `shared-elements` and `shared` -> `shared-operations`
- adding scripts `cy:run` and `cy:open`
=> cleanup in tests

.gitignore, Dockerfile.dev
In the future this should prevent unexpected behavior, when image is downloading newer version than we tested with
=> Lock pnpm version in Dockerfile to 7.5.2

apps/saleor-app-checkout/.env, apps/saleor-app-checkout/.env.template, apps/saleor-app-checkout/backend/environment.ts, apps/saleor-app-checkout/constants.ts, apps/saleor-app-checkout/mocks/consts.ts, apps/saleor-app-checkout/mocks/fixtures/saleor.ts, apps/saleor-app-checkout/test-utils.ts
Reopened PR from https://github.com/saleor/saleor-checkout/pull/189
This PR fixes saleor/react-storefront#307 issue with invariant errors caused by missing TEST_* env vars - a module that imported fixtures was used in non-testing code which caused this error
=> Fix invariant errors in API routes for TEST_* vars

.github/workflows/main.yml, packages/checkout-storefront/src/Root.tsx, packages/checkout-storefront/src/components/Skeleton/Skeleton.tsx, packages/checkout-storefront/src/fetch/types.ts, packages/checkout-storefront/src/hooks/usePay.ts, packages/checkout-storefront/src/sections/CheckoutForm/useCheckoutFinalize.ts, packages/checkout-storefront/src/sections/OrderConfirmation/OrderConfirmationSkeleton.tsx, packages/checkout-storefront/src/sections/PageNotFound.tsx
Fixes #313
- Fix Order Confirmation failing with a cryptic error because of a lack of Suspense
- Add missing OrderConfirmationSkeleton (I just put together something quickly, feel free to adjust during the redesign)
- Enable Turbo cache on GitHub Actions
=> Fix Order Confirmation failure and add OrderConfirmationSkeleton

apps/storefront/components/Footer/Footer.tsx
Fixes #355
Saleor Cloud currently doesn't support relative URLs in the footer. This is a workaround to make the links work.
=> Workaround for localhost:8000 links in the footer menu

.env
I want to remove `SALEOR_APP_TOKEN` from `.env` because:
- This variable shouldn't be stored inside a file (it's a secret)
- In development this value is taken from `.auth_token` file inside `saleor-app-checkout` after installing in Saleor
=> Remove auth token from `.env`

apps/saleor-app-checkout/pages/api/register.ts
I want to merge this because it fixes an issue when webhook registration failed in Saleor but wasn't reported back to users
=> Fix webhook registration errors not being detected

package.json
Do not override actual environmental variables when loading .env files.
=> Fix how .env files are loaded

apps/saleor-app-checkout/backend/environment.ts
This PR fixes an issue where an editor adds `\n` to the file causing errors while making requests to Saleor
=> Trim whitespaces when reading Saleor app token from `.auth_token`

apps/saleor-app-checkout/pages/api/pay.ts, packages/checkout-storefront/src/fetch/types.ts, packages/checkout-storefront/src/hooks/usePay.ts
This PR adds redirection to order confirmation page if order was created from checkout (checkout is deleted) but payment creation failed for some reason.
This gives an option to the user to retry the payment and prevents the dreaded "Checkout doesn't exist" error.
=> Redirect users to order confirmation if checkout was created

apps/saleor-app-checkout/codegen.yml, apps/saleor-app-checkout/graphql.schema.json, apps/saleor-app-checkout/graphql/index.ts, apps/storefront/codegen.yml, apps/storefront/graphql.schema.json, apps/storefront/saleor/api.tsx, packages/checkout-storefront/codegen.yml, packages/checkout-storefront/graphql.schema.json, packages/checkout-storefront/package.json, packages/checkout-storefront/src/graphql/index.ts, pnpm-lock.yaml
This PR prepends `import "graphql/language/ast"` to every TypeScript file generated via the graphql-codegen. This fixes TS2742 warnings.
=> Remove gql TypeScript TS2742 warnings and regenerate

apps/storefront/components/product/VariantSelector.tsx
Selected variants would no longer have a shadow
=> Remove shadow

apps/saleor-app-checkout/next.config.js, apps/saleor-app-checkout/tsconfig.json, package.json, packages/checkout-storefront/rollup.config.js, packages/checkout-storefront/src/lib/svgSrc.ts, packages/checkout-storefront/src/views/Checkout/Checkout.tsx, packages/checkout-storefront/src/views/index.tsx
Now modifying `packages/checkout-storefront` results in almost instant change in `apps/saleor-app-checkout`:
https://user-images.githubusercontent.com/1338731/196049167-2906ad37-8795-4829-8c5c-e187bce0beee.mp4
See https://github.com/belgattitude/nextjs-monorepo-example
=> Speedup monorepo Next.js compilation with a few hacks

.prettierignore, apps/saleor-app-checkout/README.md, docs/payment/adyen.md, docs/payment/stripe.md
Without it, stripe would hit 308 redirect and not deliver webhook
=> Add trailing slash

apps/saleor-app-checkout/backend/payments/providers/dummy/refunds.ts, apps/saleor-app-checkout/backend/payments/utils.ts, apps/saleor-app-checkout/backend/utils.ts, apps/saleor-app-checkout/pages/api/dummy-pay.ts, apps/saleor-app-checkout/pages/api/manifest.ts, apps/saleor-app-checkout/pages/api/webhooks/saleor/transaction-action-request.ts
Fixes #557
Handle refunds issued for transactions made by dummy payment provider
Fix manifest URLs when app is installed locally
=> Add refunds to dummy payment provider

packages/checkout-storefront/src/lib/utils/url.ts, packages/checkout-storefront/src/lib/utils/utils.ts
=> #635 Fix two minor bugs

.github/workflows/codeql-analysis.yml
This PR makes codeql-analysis workflow to run only on `saleor/react-storefront`.
Codeql needs to be enabled and by default the cloned repository will throw errors.
https://github.com/saleor/saleor-cli/issues/476
=> Run codeql workflow only for saleor/react-storefront

.github/workflows/e2e.yml
Missing `/` at default url causing cypress tests to fail 
```
cy.request() failed trying to load:
https://staging-demo.saleor.iographql/
We attempted to make an http request to this URL but the request failed without a response.
```
=> Fix default url in e2e workflow

apps/storefront/lib/auth/SaleorAuthClient.ts, apps/storefront/lib/auth/types.ts, packages/checkout-storefront/src/hooks/useCheckoutFormValidationTrigger.ts, packages/checkout-storefront/src/hooks/useForm/useForm.ts, packages/checkout-storefront/src/lib/auth/SaleorAuthClient.ts, packages/checkout-storefront/src/lib/auth/types.ts, packages/checkout-storefront/src/sections/AddressList/useAddressListForm.ts, packages/checkout-storefront/src/sections/CheckoutForm/useCheckoutSubmit.ts, packages/checkout-storefront/src/sections/DeliveryMethods/DeliveryMethods.tsx, packages/checkout-storefront/src/sections/DeliveryMethods/useDeliveryMethodsForm.ts, packages/checkout-storefront/src/sections/GuestBillingAddressSection/useBillingSameAsShippingForm.ts, packages/checkout-storefront/src/sections/PaymentSection/AdyenDropIn/AdyenDropIn.tsx, packages/checkout-storefront/src/sections/Summary/useSummaryHeightCalc.ts, packages/checkout-storefront/src/state/updateStateStore.ts
Fixes: 
- saleor auth client falling in loop when refresh token is expired
- "billing address not set" error being thrown within payment in some cases
- summary closing unexpectedly after opening on mobile view
- remove some leftover console.logs
Also added a skeleton for delivery methods. Currently when logged in user has no shipping address set but the auto selection is in progress, the section says "please fill in the shipping address first" - while that makes sense for the guest user, for signed in one it's already happening so it makes more sense to replace the bit with skeleton that'll actually indicate loading to user instead of requirement for action.
=> Various small fixes

apps/saleor-app-checkout/.env
It adds back missing env in `saleor-app-checkout` that's used in https://github.com/saleor/react-storefront/blob/canary/apps/saleor-app-checkout/frontend/misc/client.ts
=> Fix env file - missing `NEXT_PUBLIC_SALEOR_API_URL`

packages/ui-kit/src/components/Select/Select.tsx
We shouldn't assume `value` as key in the `Select` component, an example is the Japan area.
The GraphQL query:
```graphql
{
addressValidationRules(countryCode: JP) {
countryAreaChoices {
raw
verbose
}
}
}
```
The response:
```
{
"data": {
"addressValidationRules": {
"countryAreaChoices": [
{
"raw": "北海道",
"verbose": "Hokkaido"
},
{
"raw": "北海道",
"verbose": "北海道"
},
...
```
The `raw` value is not unique so that it can't be used as the key.
In almost all cases, the options list are always fully updated, so I guess the fix will not introduce real performance issue.
=> fix: duplicated key in country area Select

src/ui/components/VariantSelector.tsx
Some products have variants with labels that do not fit within the button container when a fixed width is set using `grid`. To address this, I suggest using `flex` instead.
=> fix: Improve the display of variant selector items.

src/app/cart/page.tsx, src/app/categories/[slug]/page.tsx, src/app/error.tsx, src/app/login/page.tsx, src/app/products/[slug]/page.tsx, src/app/products/page.tsx, src/checkout/components/AddressSkeleton.tsx, src/checkout/components/Button.tsx, src/checkout/components/Divider/Divider.tsx, src/checkout/components/SelectBox/SelectBox.tsx, src/checkout/components/TextInput.tsx, src/checkout/sections/DeliveryMethods/DeliveryMethodsSkeleton.tsx, src/checkout/sections/PageHeader/LanguageSelect.tsx, src/checkout/sections/PaymentSection/PaymentSectionSkeleton.tsx, src/checkout/views/EmptyCartPage/EmptyCartPage.tsx, src/checkout/views/OrderConfirmation/OrderConfirmationSkeleton.tsx, src/ui/atoms/Loader.tsx, src/ui/components/ActiveLink.tsx, src/ui/components/Footer.tsx, src/ui/components/LoginForm.tsx, src/ui/components/Nav.tsx, src/ui/components/Pagination.tsx, src/ui/components/Topbar.tsx, src/ui/components/UserCard.tsx
I'm unsure if it's a good idea, but recently, with [this PR](https://github.com/saleor/storefront/pull/914), the colors on the product page were changed to gray. Perhaps we should consider standardizing colors across the entire app? This PR changes element colors to `gray` from `slate` throughout the entire application.
=> fix: unify colors across the entire app

src/ui/atoms/ProductImageWrapper.tsx
I am so sorry, but in my recent [PR](https://github.com/saleor/storefront/pull/912), I accidentally lost the most important part of the code after merging with the canary branch 😬. This pull request delivers it once more and resolves the #911 issue.
=> fix: fix tile size

src/app/(main)/cart/page.tsx, src/app/(main)/categories/[slug]/page.tsx, src/app/(main)/page.tsx, src/app/(main)/products/[slug]/page.tsx, src/app/(main)/products/page.tsx, src/ui/components/ProductElement.tsx, src/ui/components/ProductList.tsx, src/ui/components/Topbar.tsx
- Unify style of the product lists in app - grid breakpoints, spacings and widths.
- Add the `sizes` attribute to the images in the product list to provide the browser with more information about how much space they occupy on the screen - it should improve overall lighthouse performance score.
- Add the `priority` property to the thumbnail on product page because it is LCP element on that page.
- Add missed margin in cart.
=> fix: improve performance and styles

src/ui/components/ProductElement.tsx, src/ui/components/ProductList.tsx
First image in the grid gets high loading prio
=> Add prio to first image

src/ui/components/VariantSelector.tsx
I suggest disabling the `scroll` behavior for links in the variant selector. Why? Especially on mobile devices, it can be a bit annoying that the page scrolls to the top every time the user changes the product variant. In some cases, all variants are visible only after scrolling down the page, as we have product thumbnails at the top.
=> fix: disable scroll for the links in the variant selector

src/app/(main)/cart/page.tsx
Display product variant in cart only if variant name isn't empty and is different than variant id.
The default variant name is the same as its identifier, so if the name differs from the identifier, the user must have edited it for some reason, and we want to display that. If the user has cleared the variant name, we also do not want to display it.
=> fix: fix product variant information in cart

src/checkout/sections/CheckoutForm/CheckoutForm.tsx, src/checkout/sections/SignIn/SignIn.tsx
- Fix #976 issue by removing divider (horizontal line) and adding 1rem vertical padding on Sign In button
=> fix(checkout): remove divider in SignIn sections and add vertical padding on Sign In button

src/checkout/sections/Summary/Summary.tsx
=> fix: remove unnecessary currency symbol from checkout summary

src/checkout/components/AddressForm/AddressForm.tsx, src/checkout/components/IconButton.tsx, src/checkout/components/ManualSaveAddressForm/AddressFormActions.tsx, src/checkout/components/PasswordInput/PasswordInput.tsx, src/checkout/components/Select.tsx, src/checkout/components/TextInput.tsx, src/checkout/sections/Contact/SignInFormContainer.tsx, src/checkout/sections/GuestUser/GuestUser.tsx, src/checkout/sections/ResetPassword/ResetPassword.tsx, src/checkout/sections/SignIn/SignIn.tsx, src/checkout/sections/Summary/SummaryItem.tsx, src/checkout/sections/Summary/SummaryItemMoneyInfo.tsx, src/checkout/sections/Summary/SummaryPromoCodeRow.tsx
Proposal for solving #992 issue.
I have rewritten the `PasswordInput` component. Most of its code comes from the `TextInput` component because I couldn't found any good way to change styles, except by inserting the `IconButton` into old `PasswordInput` component structure including its functionality to change input field type.
Also introduced some style adjustments.
=> fix: fix reveal password button in password input field

src/app/(main)/cart/page.tsx
1. Link to checkout on mobile view - before / after:
2. Fix the condition that determines when to display information about an empty cart. This should cover cases where a user creates a cart but removes all items from it.
=> fix: styles and empty cart info

src/app/(main)/layout.tsx, src/app/layout.tsx
Before (red overlay isn't a part of this PR and was added to easier notice a problem): 
https://github.com/saleor/storefront/assets/27455716/a2916b1c-8c5a-4d41-b894-ba7961129ab3
After:
https://github.com/saleor/storefront/assets/27455716/5adfb74f-0572-4da5-8a17-cc2d952ea420
=> fix: fix disappearing sticky header

src/app/(main)/cart/page.tsx, src/app/checkout/page.tsx, src/checkout/assets/icons/edit.tsx, src/checkout/components/AddressForm/AddressForm.tsx, src/checkout/components/AddressForm/useAddressFormUtils.ts, src/checkout/components/AddressSelectBox/AddressSelectBox.tsx, src/checkout/components/Button.tsx, src/checkout/components/CountrySelect.tsx, src/checkout/components/ManualSaveAddressForm/AddressFormActions.tsx, src/checkout/sections/AddressList/AddressList.tsx, src/checkout/sections/DeliveryMethods/DeliveryMethods.tsx, src/checkout/sections/PaymentSection/errorMessages.ts, src/checkout/sections/Summary/SummaryPromoCodeRow.tsx
1. Change missleading link destination:
2. Align remove voucher code button:
from:
to:
3. Adjust edit button in shipping address list:
4. Fix checkout background to fill whole height of the viewport even when checkout content still loading to prevent strange layout shift.
5. Fix button styles.
6. Improve a11y of the Edit Shipping address form.
7. Add label for prefecture select field.
8. Set to full width country select field to standardize fields in shipping address form.
9. Add missed error message when discount cupon cannot be applied to the current order.
=> fix: fix styles in checkout

src/ui/components/ChannelSelect.tsx, src/ui/components/Footer.tsx
=> Add currency select

src/ui/components/AvailabilityMessage.tsx, src/ui/components/VariantSelector.tsx
Design adjustments to make the layout look neater
=> Design nudges

src/checkout/sections/PaymentSection/PaymentMethods.tsx
Previously:
PaymentMethods was trying to import components even if those were not defined in the `paymentMethodToComponent` mapping. It was leading to errors if API returned gateway ID not known to the storefront.
After this change:
List of payment gateways is filtered by known implementations, and only those will be displayed.
=> Add check for payments section to only display implemented payment gateways
